apiVersion: v1
kind: PersistentVolume
metadata:
  name: metrics-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/transformations

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metrics-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

