version: '3'

services:
  cassandra_db:
    container_name: cassandra_db
    image: cassandra_db:4.0
    #restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9042:9042"
    #network_mode: host