apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: loading-raw-data
  namespace: airflow
spec:
  type: Scala
  mode: cluster
  sparkVersion: "3.2.1"
  image: loading_raw_data:1.0
  imagePullPolicy: Never
  mainClass: com.cognira.loadingRawData.Main
  mainApplicationFile: "local:///opt/target/scala-2.12/loading_raw_data_2.12-0.1.jar"
  restartPolicy:
    type: Never
  driver:
    cores: 2
    coreLimit: "2"
    memory: "2g"
    serviceAccount: spark-operator-spark
    javaOptions: "-Dlog4j.configuration=file:/app/src/main/resources/log4j.properties"
  executor:
    cores: 2
    coreLimit: "2"
    memory: "1g"
  sparkConf:
      spark.cassandra.auth.username: "cassandra"
      spark.cassandra.auth.password: "cassandra"

  
