apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: airflow
spec:
  type: Scala
  mode: cluster
  sparkVersion: "3.2.1"
  image: loading_raw_data:1.0
  imagePullPolicy: Never
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.12-3.2.1.jar"
  restartPolicy:
    type: Never
  driver:
    cores: 2
    coreLimit: "2"
    memory: "3g"
    serviceAccount: spark-operator-spark
  executor:
    cores: 2
    coreLimit: "2"
    memory: "1g"
    instances: 1
