version: '3'

services:
  processing_data:
    image: processing_data:1.0
    container_name: processing_data
    build:
      context: ./
      dockerfile: Dockerfile
#     network_mode: host
#     volumes:
#       - metrics:/opt/transformations

# volumes:
#   metrics:
#     external: true
