apiVersion: batch/v1
kind: Job
metadata:
  name: checking-data-quality
  namespace: spark-kubernetes
spec:
  template:
    spec:
      containers:
      - name: checking-data-quality
        image: checking_data_quality:1.0
        imagePullPolicy: Never
        command: [
          "/bin/bash",
          "-c",
          "/opt/spark/bin/spark-submit \
          --master k8s://https://kind-control-plane:6443 \ 
          --deploy-mode cluster \
          --name checking-data-quality \
          --class com.cognira.checking.Main \
          --driver-java-options -Dlog4j.configuration=file:/app/src/main/resources/log4j.properties \
          --conf spark.cassandra.auth.username=cassandra \
          --conf spark.cassandra.auth.password=cassandra \
          --conf spark.executor.instances=3 \
          --conf spark.kubernetes.authenticate.driver.serviceAccountName=spark \
          --conf spark.kubernetes.namespace=spark-kubernetes \
          --conf spark.kubernetes.container.image=checking_data_quality:1.0 \
          --conf spark.kubernetes.container.image.pullPolicy=Never \
          --conf spark.driver.host=$(hostname -i) \
          --conf spark.driver.pod.name=$(hostname) \
          --conf spark.dynamicAllocation.shuffleTracking.enabled=false \
          --conf spark.dynamicAllocation.enabled=false \
          --conf spark.kubernetes.executor.deleteOnTermination=true \
          --conf spark.kubernetes.driver.pod.name=checking-data-quality-driver \
          local:///opt/target/scala-2.12/checking_data_quality_2.12-0.1.jar"
        ]
      restartPolicy: Never
      serviceAccountName: spark
  backoffLimit: 2
