apiVersion: batch/v1
kind: Job
metadata:
  name: processing
  namespace: spark-kubernetes
spec:
  template:
    spec:
      volumes:
      - name: metrics
        persistentVolumeClaim:
            claimName: metrics-pvc
      containers:
      - name: processing-data
        image: processing_data:1.0
        imagePullPolicy: Never
        volumeMounts:
          - name: metrics
            mountPath: /opt/transformations
        command: [
           "/bin/bash",
           "-c",
           "/opt/spark/bin/spark-submit \
           --master k8s://https://kind-control-plane:6443 \ 
           --deploy-mode cluster \
           --name processing-data \
           --class com.cognira.processing.Main \
           --driver-java-options -Dlog4j.configuration=file:/app/src/main/resources/log4j.properties \
           --conf spark.executor.instances=3 \
           --conf spark.kubernetes.authenticate.driver.serviceAccountName=spark \
           --conf spark.kubernetes.namespace=spark-kubernetes \
           --conf spark.kubernetes.container.image=processing_data:1.0 \
           --conf spark.kubernetes.container.image.pullPolicy=Never \
           --conf spark.driver.host=$(hostname -i) \
           --conf spark.driver.pod.name=$(hostname) \
           --conf spark.dynamicAllocation.shuffleTracking.enabled=false \
           --conf spark.dynamicAllocation.enabled=false \
           --conf spark.kubernetes.executor.deleteOnTermination=true \
           --conf spark.kubernetes.driver.pod.name=processing-data-driver \
           --conf spark.kubernetes.driver.volumes.persistentVolumeClaim.metrics-pvc.options.claimName=metrics-pvc \
           --conf spark.kubernetes.driver.volumes.persistentVolumeClaim.metrics-pvc.mount.path=/opt/transformations \
           --conf spark.kubernetes.executor.volumes.persistentVolumeClaim.metrics-pvc.options.claimName=metrics-pvc \
           --conf spark.kubernetes.executor.volumes.persistentVolumeClaim.metrics-pvc.mount.path=/opt/transformations \
           local:///opt/target/scala-2.12/processing_2.12-0.1.jar"
        ]
      restartPolicy: Never
      serviceAccountName: spark
  backoffLimit: 2
