apiVersion: batch/v1
kind: Job
metadata:
  name: spark-pi
  namespace: spark-kubernetes
spec:
  template:
    spec:
      containers:
      - name: spark-pi
        image: processing:1.0
        imagePullPolicy: Never
        command: [
           "/bin/bash",
           "-c",
           "/opt/spark/bin/spark-submit \ 
           --deploy-mode cluster \
           --name spark-pi \
           --master k8s://https://kind-control-plane:6443 \
           --class org.apache.spark.examples.SparkPi \
           --conf spark.executor.instances=2 \
           --conf spark.kubernetes.authenticate.driver.serviceAccountName=spark \
           --conf spark.kubernetes.namespace=spark-kubernetes \
           --conf spark.kubernetes.container.image=processing:1.0 \
           --conf spark.kubernetes.container.image.pullPolicy=Never \
           --conf spark.driver.host=$(hostname -i) \
           --conf spark.driver.pod.name=$(hostname) \
           --conf spark.dynamicAllocation.shuffleTracking.enabled=false \
           --conf spark.dynamicAllocation.enabled=false \
           --conf spark.kubernetes.executor.deleteOnTermination=true \
           local:///opt/spark/examples/jars/spark-examples_2.12-3.2.1.jar 10"
        ]
      restartPolicy: Never
      serviceAccountName: spark
  backoffLimit: 2
